region(auvergneRhôneAlpes).
region(bourgogneFrancheComte).
region(bretagne).
region(centreValDeLoire).
region(corse).
region(grandEst).
region(hautsDeFrance).
region(ileDeFrance).
region(normandie).
region(nouvelleAquitaine).
region(occitanie).
region(paysDeLaLoire).
region(provenceAlpesCoteDAzur).